# Generated by Django 3.2.13 on 2022-04-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sajatuser',
            name='azonosito',
            field=models.CharField(default='0', max_length=11),
            preserve_default=False,
        ),
    ]
