# Generated by Django 3.2.13 on 2022-05-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_sajatuser_azonosito'),
    ]

    operations = [
        migrations.AddField(
            model_name='sajatuser',
            name='nev',
            field=models.CharField(default='Szaros', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sajatuser',
            name='pontszam',
            field=models.CharField(default=4, max_length=255),
            preserve_default=False,
        ),
    ]
